from edc_visit_schedule import FormsCollection, Crf

crfs_d1 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.patienthistory'),
    Crf(show_order=2, model='ambition_subject.medicalexpenses'),
    Crf(show_order=3, model='ambition_subject.medicalexpensestwo',
        required=False),
    Crf(show_order=4, model='ambition_subject.education'),
    Crf(show_order=5, model='ambition_subject.educationhoh', required=False),
    Crf(show_order=6, model='ambition_subject.bloodresult'),
    Crf(show_order=7, model='ambition_subject.lumbarpuncturecsf'),
    Crf(show_order=8, model='ambition_subject.prnmodel'),
    Crf(show_order=9, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=10, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=11, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=12, model='ambition_subject.microbiology', required=False),
    Crf(show_order=13, model='ambition_subject.radiology', required=False),
    Crf(show_order=14, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=15, model='ambition_subject.deathreport', required=False),
    Crf(show_order=16, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=17, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=18, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=19, model='ambition_subject.subjectoffstudy',
        required=False))

crfs_d3 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.bloodresult'),
    Crf(show_order=2, model='ambition_subject.prnmodel'),
    Crf(show_order=3, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=4, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=5, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=6, model='ambition_subject.microbiology', required=False),
    Crf(show_order=7, model='ambition_subject.radiology', required=False),
    Crf(show_order=8, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=9, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=10, model='ambition_subject.deathreport', required=False),
    Crf(show_order=11, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=13, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=14, model='ambition_subject.subjectoffstudy',
        required=False))

crfs_d5 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.bloodresult'),
    Crf(show_order=2, model='ambition_subject.prnmodel'),
    Crf(show_order=3, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=4, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=5, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=6, model='ambition_subject.microbiology', required=False),
    Crf(show_order=7, model='ambition_subject.radiology', required=False),
    Crf(show_order=8, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=9, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=10, model='ambition_subject.deathreport', required=False),
    Crf(show_order=11, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=13, model='ambition_subject.recurrencesymptom',
        required=False),)

crfs_d7 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.bloodresult'),
    Crf(show_order=2, model='ambition_subject.lumbarpuncturecsf'),
    Crf(show_order=3, model='ambition_subject.prnmodel'),
    Crf(show_order=4, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=5, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=6, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=7, model='ambition_subject.microbiology', required=False),
    Crf(show_order=8, model='ambition_subject.radiology', required=False),
    Crf(show_order=9, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=10, model='ambition_subject.deathreport', required=False),
    Crf(show_order=11, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=13, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=14, model='ambition_subject.subjectoffstudy',
        required=False))

crfs_d10 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.bloodresult'),
    Crf(show_order=2, model='ambition_subject.prnmodel'),
    Crf(show_order=3, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=4, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=5, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=6, model='ambition_subject.microbiology', required=False),
    Crf(show_order=7, model='ambition_subject.radiology', required=False),
    Crf(show_order=8, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=9, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=10, model='ambition_subject.deathreport',
        required=False),
    Crf(show_order=11, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=13, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=14, model='ambition_subject.subjectoffstudy',
        required=False),)

crfs_d12 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.bloodresult'),
    Crf(show_order=2, model='ambition_subject.prnmodel'),
    Crf(show_order=3, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=4, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=5, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=6, model='ambition_subject.microbiology', required=False),
    Crf(show_order=7, model='ambition_subject.radiology', required=False),
    Crf(show_order=8, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=9, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=10, model='ambition_subject.deathreport', required=False),
    Crf(show_order=11, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=13, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=14, model='ambition_subject.subjectoffstudy',
        required=False),)

crfs_d14 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.bloodresult'),
    Crf(show_order=2, model='ambition_subject.lumbarpuncturecsf'),
    Crf(show_order=3, model='ambition_subject.week2'),
    Crf(show_order=4, model='ambition_subject.prnmodel'),
    Crf(show_order=5, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=6, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=7, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=8, model='ambition_subject.microbiology', required=False),
    Crf(show_order=9, model='ambition_subject.radiology', required=False),
    Crf(show_order=10, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=11, model='ambition_subject.deathreport', required=False),
    Crf(show_order=12, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=13, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=14, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=15, model='ambition_subject.subjectoffstudy',
        required=False))

crfs_w4 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.week4'),
    Crf(show_order=2, model='ambition_subject.bloodresult'),
    Crf(show_order=3, model='ambition_subject.prnmodel'),
    Crf(show_order=4, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=5, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=6, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=7, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=8, model='ambition_subject.microbiology', required=False),
    Crf(show_order=9, model='ambition_subject.radiology', required=False),
    Crf(show_order=10, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=11, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreport', required=False),
    Crf(show_order=13, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=14, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=15, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=16, model='ambition_subject.subjectoffstudy',
        required=False),)

crfs_w6 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.followup'),
    Crf(show_order=2, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=3, model='ambition_subject.prnmodel'),
    Crf(show_order=4, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=5, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=6, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=7, model='ambition_subject.bloodresult', required=False),
    Crf(show_order=8, model='ambition_subject.microbiology', required=False),
    Crf(show_order=9, model='ambition_subject.radiology', required=False),
    Crf(show_order=10, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=11, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreport', required=False),
    Crf(show_order=13, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=14, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=15, model='ambition_subject.subjectoffstudy',
        required=False),)

crfs_w8 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.followup'),
    Crf(show_order=2, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=3, model='ambition_subject.prnmodel'),
    Crf(show_order=4, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=5, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=6, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=7, model='ambition_subject.bloodresult', required=False),
    Crf(show_order=8, model='ambition_subject.microbiology', required=False),
    Crf(show_order=9, model='ambition_subject.radiology', required=False),
    Crf(show_order=10, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=11, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreport', required=False),
    Crf(show_order=13, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=14, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=15, model='ambition_subject.subjectoffstudy',
        required=False))

crfs_w10 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.followup'),
    Crf(show_order=2, model='ambition_subject.medicalexpenses'),
    Crf(show_order=3, model='ambition_subject.medicalexpensestwo'),
    Crf(show_order=4, model='ambition_subject.studyterminationconclusion'),
    Crf(show_order=5, model='ambition_subject.recurrencesymptom',
        required=False),
    Crf(show_order=6, model='ambition_subject.prnmodel'),
    Crf(show_order=7, model='ambition_subject.adverseevent', required=False),
    Crf(show_order=8, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=9, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=10, model='ambition_subject.bloodresult', required=False),
    Crf(show_order=11, model='ambition_subject.microbiology', required=False),
    Crf(show_order=12, model='ambition_subject.radiology', required=False),
    Crf(show_order=13, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=14, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=15, model='ambition_subject.deathreport',
        required=False),
    Crf(show_order=16, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=17, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=18, model='ambition_subject.subjectoffstudy',
        required=False))

crfs_w16 = FormsCollection(
    Crf(show_order=1, model='ambition_subject.week16'),
    Crf(show_order=2, model='ambition_subject.deathreport', required=False),
    Crf(show_order=3, model='ambition_subject.subjectoffstudy',
        required=False),)

crfs_unscheduled = FormsCollection(
    Crf(show_order=1, model='ambition_subject.prnmodel'),
    Crf(show_order=2,
        model='ambition_subject.adverseevent', required=False),
    Crf(show_order=3, model='ambition_subject.adverseeventtmg',
        required=False),
    Crf(show_order=4, model='ambition_subject.adverseeventfollowup',
        required=False),
    Crf(show_order=5, model='ambition_subject.bloodresult',
        required=False),
    Crf(show_order=6,
        model='ambition_subject.microbiology', required=False),
    Crf(show_order=7, model='ambition_subject.radiology',
        required=False),
    Crf(show_order=8, model='ambition_subject.protocoldeviationviolation',
        required=False),
    Crf(show_order=9, model='ambition_subject.lumbarpuncturecsf',
        required=False),
    Crf(show_order=10, model='ambition_subject.deathreport',
        required=False),
    Crf(show_order=11, model='ambition_subject.deathreporttmg1',
        required=False),
    Crf(show_order=12, model='ambition_subject.deathreporttmg2',
        required=False),
    Crf(show_order=13, model='ambition_subject.subjectoffstudy',
        required=False))
